# Generated by Django 3.2.12 on 2022-05-09 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_api', '0008_delete_recognizemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognizeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField()),
                ('mushroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_api.mushroom')),
            ],
        ),
    ]
