# Generated by Django 3.0.5 on 2020-05-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.ManyToManyField(blank=True, default=list, related_name='_user_notes_+', to='users.Note'),
        ),
    ]
