# SECURITY WARNING: keep the secret key used in production secret!
secret_key: di=w0msq$xeus9h)_rwbt)_nombdz%gwf1z$^1gg6+tdprg-vl
media_url: /media/
databases:
  default:
    ENGINE: django.contrib.gis.db.backends.postgis
    NAME: gis
    USER: user001
    PASSWORD: 123456789
    HOST: 127.0.0.1
    PORT: 5432

static_url: /static/