# Generated by Django 3.0.5 on 2020-05-05 20:15

from django.db import migrations, models
import django.db.models.deletion
import rest_framework.generics
import rest_framework.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('base_api', '0002_user_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mushroomplace',
            name='mushroom',
        ),
        migrations.CreateModel(
            name='RecognizeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField()),
                ('mushroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_api.Mushroom')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, rest_framework.mixins.ListModelMixin, rest_framework.generics.GenericAPIView),
        ),
    ]
