# Generated by Django 3.2.12 on 2022-05-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_api', '0005_auto_20200506_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
