# Generated by Django 3.2.12 on 2022-05-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_api', '0007_note_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecognizeModel',
        ),
    ]
